"use client";

import React, { useState, useEffect } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Loader2, AlertCircle, Sparkles, Link2, Copy, Check, Info } from "lucide-react";
import { CreateCampaignData, UTMParameter } from "@/types/campaign";
import { campaignApi } from "@/services/campaign/campaign";
import { useGoogleAds } from "@/contexts/GoogleAdsContext";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { GoogleAdsCampaignError } from "@/types/errors";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
// import { useToast } from "@/hooks/use-toast";

interface CreateCampaignDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

// UTM Parameter descriptions
const UTM_DESCRIPTIONS: Record<string, string> = {
  utm_source: "Identifies which site sent the traffic (e.g., google, newsletter)",
  utm_medium: "Identifies what type of link was used (e.g., cpc, email, social)",
  utm_campaign: "Identifies a specific campaign (e.g., summer_sale)",
  utm_id: "Campaign ID for tracking specific campaigns",
  utm_term: "Identifies search keywords (dynamic keyword insertion)",
  utm_content: "Identifies what specifically was clicked (e.g., ad creative)",
};

export function CreateCampaignDialog({ open, onOpenChange }: CreateCampaignDialogProps) {
  const queryClient = useQueryClient();
  const { status, isSwitchingAccount } = useGoogleAds();
  // const { toast } = useToast();
  const [formData, setFormData] = useState<CreateCampaignData>({
    name: "",
    google_ads_campaign_id: "",
    google_ads_customer_id: "",
    utm_params: [],
  });
  const [selectedGoogleAdsCampaign, setSelectedGoogleAdsCampaign] = useState<any | null>(null);
  const [autoGeneratedUTMs, setAutoGeneratedUTMs] = useState<UTMParameter[]>([]);
  const [copiedUrl, setCopiedUrl] = useState(false);

  const { data: googleAdsCampaigns, isLoading: googleAdsCampaignsLoading, error: fetchError } = useQuery<
    any[],
    GoogleAdsCampaignError
  >({
    queryKey: ["googleAdsCampaigns", status?.customer_id],
    queryFn: async () => {
      const result = await campaignApi.googleAdsCampaign(status?.customer_id || "");
      return result;
    },
    enabled: !!status?.customer_id && !isSwitchingAccount,
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  });

  // Auto-generate UTM parameters when campaign is selected
  useEffect(() => {
    if (selectedGoogleAdsCampaign) {
      const campaignName = selectedGoogleAdsCampaign.name;
      const campaignId = selectedGoogleAdsCampaign.id;
      
      // Generate slug from campaign name
      const slug = campaignName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');

      const utmParams: UTMParameter[] = [
        { 
          key: 'utm_source', 
          value: 'google', 
          selected: true,
          description: UTM_DESCRIPTIONS.utm_source
        },
        { 
          key: 'utm_medium', 
          value: 'cpc', 
          selected: true,
          description: UTM_DESCRIPTIONS.utm_medium
        },
        { 
          key: 'utm_campaign', 
          value: slug, 
          selected: true,
          description: UTM_DESCRIPTIONS.utm_campaign
        },
        { 
          key: 'utm_id', 
          value: campaignId, 
          selected: true,
          description: UTM_DESCRIPTIONS.utm_id
        },
        { 
          key: 'utm_term', 
          value: '{keyword}', 
          selected: false,
          description: UTM_DESCRIPTIONS.utm_term
        },
        { 
          key: 'utm_content', 
          value: '{creative}', 
          selected: false,
          description: UTM_DESCRIPTIONS.utm_content
        },
      ];

      setAutoGeneratedUTMs(utmParams);
      setFormData(prev => ({
        ...prev,
        name: campaignName,
        google_ads_campaign_id: campaignId,
        google_ads_customer_id: status?.customer_id || "",
        utm_params: utmParams,
        google_ads_campaign_data: selectedGoogleAdsCampaign,
      }));
    }
  }, [selectedGoogleAdsCampaign, status?.customer_id]);

  // Reset when customer changes
  useEffect(() => {
    if (status?.customer_id) {
      setSelectedGoogleAdsCampaign(null);
      setAutoGeneratedUTMs([]);
    }
  }, [status?.customer_id]);

  const createMutation = useMutation({
    mutationFn: campaignApi.create,
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["campaigns"] });
      // toast({
      //   title: "Campaign Created",
      //   description: `Campaign "${data.name}" has been created successfully.`,
      //   variant: "default",
      // });
      onOpenChange(false);
      resetForm();
    },
    onError: (error: any) => {
      // toast({
      //   title: "Error Creating Campaign",
      //   description: error?.message || "Failed to create campaign. Please try again.",
      //   variant: "destructive",
      // });
    },
  });

  const resetForm = () => {
    setFormData({
      name: "",
      google_ads_campaign_id: "",
      google_ads_customer_id: "",
      utm_params: [],
    });
    setSelectedGoogleAdsCampaign(null);
    setAutoGeneratedUTMs([]);
    setCopiedUrl(false);
  };

  const handleUTMToggle = (index: number) => {
    setAutoGeneratedUTMs(prev => {
      const updated = [...prev];
      updated[index] = { ...updated[index], selected: !updated[index].selected };
      
      // Update formData with the new UTM selection
      setFormData(prevForm => ({
        ...prevForm,
        utm_params: updated,
      }));
      
      return updated;
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedGoogleAdsCampaign) {
      // toast({
      //   title: "Selection Required",
      //   description: "Please select a Google Ads campaign.",
      //   variant: "destructive",
      // });
      return;
    }

    const selectedUTMs = autoGeneratedUTMs.filter(utm => utm.selected);
    if (selectedUTMs.length === 0) {
      // toast({
      //   title: "No UTM Parameters Selected",
      //   description: "Please select at least one UTM parameter.",
      //   variant: "destructive",
      // });
      return;
    }

    createMutation.mutate({
      ...formData,
      utm_params: autoGeneratedUTMs, // Send all UTMs with selected flag
    });
  };

  const generateTrackingUrl = () => {
    const baseUrl = "https://yourwebsite.com/";
    const selectedUTMs = autoGeneratedUTMs.filter(utm => utm.selected);
    const params = selectedUTMs.map(utm => `${utm.key}=${utm.value}`).join('&');
    return params ? `${baseUrl}?${params}` : baseUrl;
  };

  const copyTrackingUrl = () => {
    navigator.clipboard.writeText(generateTrackingUrl());
    setCopiedUrl(true);
    // toast({
    //   title: "Copied!",
    //   description: "Tracking URL copied to clipboard.",
    // });
    setTimeout(() => setCopiedUrl(false), 2000);
  };

  const isLoading = googleAdsCampaignsLoading || isSwitchingAccount;
  const isFormDisabled = isLoading || createMutation.isPending;
  const selectedCount = autoGeneratedUTMs.filter(utm => utm.selected).length;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-green-600" />
            Create New Campaign
          </DialogTitle>
          <DialogDescription>
            Select a Google Ads campaign and choose which UTM parameters to track.
          </DialogDescription>
        </DialogHeader>

        {isSwitchingAccount && (
          <Alert className="mb-4">
            <Loader2 className="h-4 w-4 animate-spin" />
            <AlertDescription>
              Switching accounts... Please wait while we load your campaigns.
            </AlertDescription>
          </Alert>
        )}

        {fetchError && !isSwitchingAccount && (
          <Alert variant="destructive" className="mb-4">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <p className="text-sm font-medium mb-2">Error: {fetchError.message}</p>
              {fetchError.customer_id && (
                <div className="text-xs space-y-1">
                  <p>Customer ID: <code className="bg-destructive/20 px-1 py-0.5 rounded">{fetchError.customer_id}</code></p>
                  {fetchError.customer_name && <p>Account: {fetchError.customer_name}</p>}
                  {fetchError.error_code && <p>Error Code: <code className="bg-destructive/20 px-1 py-0.5 rounded">{fetchError.error_code}</code></p>}
                  {/* {fetchError.is_manager && (
                    <p className="mt-2 text-xs">
                      💡 Manager accounts cannot track campaigns directly. Please select a client account from the sidebar.
                    </p>
                  )} */}
                </div>
              )}
            </AlertDescription>
          </Alert>
        )}

        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            {/* Campaign Selection */}
            <div className="space-y-2">
              <Label htmlFor="googleAdsCampaign">
                Select Google Ads Campaign *
              </Label>
              {isLoading ? (
                <Select disabled>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder={isSwitchingAccount ? "Switching accounts..." : "Loading campaigns..."} />
                  </SelectTrigger>
                </Select>
              ) : googleAdsCampaigns?.length === 0 ? (
                <div className="p-4 border rounded-md bg-muted text-center">
                  <p className="text-sm text-gray-600">No Google Ads campaigns found for this account.</p>
                </div>
              ) : (
                <Select
                  onValueChange={(value) => {
                    const campaign = googleAdsCampaigns?.find(c => c.id === value);
                    setSelectedGoogleAdsCampaign(campaign);
                  }}
                  value={selectedGoogleAdsCampaign?.id || ""}
                  disabled={isFormDisabled}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select a campaign" />
                  </SelectTrigger>
                  <SelectContent>
                    {googleAdsCampaigns?.map((campaign: any) => (
                      <SelectItem key={campaign.id} value={campaign.id}>
                        <div className="flex items-center justify-between gap-2 w-full">
                          <span className="truncate">{campaign.name}</span>
                          <Badge variant={campaign.status === 'ENABLED' ? 'default' : 'secondary'} className="ml-2 text-xs shrink-0">
                            {campaign.status}
                          </Badge>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>

            {/* Campaign Name (Auto-filled) */}
            <div className="space-y-2">
              <Label htmlFor="name">Campaign Name</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="Auto-filled from Google Ads"
                disabled={isFormDisabled}
                className="bg-muted"
              />
            </div>

            {/* UTM Parameter Selection */}
            {autoGeneratedUTMs.length > 0 && (
              <Card className="border-blue-200 bg-blue-50/30">
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="text-sm flex items-center gap-2">
                        <Sparkles className="h-4 w-4 text-blue-600" />
                        Select UTM Parameters
                      </CardTitle>
                      <CardDescription className="text-xs">
                        Choose which tracking parameters to include ({selectedCount} selected)
                      </CardDescription>
                    </div>
                    <Badge variant="secondary" className="text-xs">
                      {selectedCount}/{autoGeneratedUTMs.length}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-2">
                  {autoGeneratedUTMs.map((utm, idx) => (
                    <div
                      key={idx}
                      className={`
                        flex items-start gap-3 p-3 rounded-lg border transition-all
                        ${utm.selected 
                          ? 'bg-white border-blue-200 shadow-sm' 
                          : 'bg-gray-50 border-gray-200 opacity-60'
                        }
                      `}
                    >
                      <Checkbox
                        id={`utm-${idx}`}
                        checked={utm.selected}
                        onCheckedChange={() => handleUTMToggle(idx)}
                        disabled={isFormDisabled}
                        className="mt-1"
                      />
                      <div className="flex-1 min-w-0">
                        <Label
                          htmlFor={`utm-${idx}`}
                          className="text-sm font-medium cursor-pointer flex items-center gap-2"
                        >
                          <code className="text-xs bg-blue-100 px-2 py-0.5 rounded font-mono">
                            {utm.key}
                          </code>
                          <span className="text-gray-600">=</span>
                          <code className="text-xs bg-gray-100 px-2 py-0.5 rounded font-mono truncate">
                            {utm.value}
                          </code>
                        </Label>
                        {utm.description && (
                          <p className="text-xs text-gray-600 mt-1 flex items-start gap-1">
                            <Info className="h-3 w-3 mt-0.5 flex-shrink-0" />
                            {utm.description}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}

                  {/* Tracking URL Preview */}
                  {selectedCount > 0 && (
                    <div className="space-y-2 pt-3 border-t">
                      <Label className="text-xs flex items-center gap-1">
                        <Link2 className="h-3 w-3" />
                        Tracking URL Preview
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          value={generateTrackingUrl()}
                          readOnly
                          className="font-mono text-xs bg-white"
                        />
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          onClick={copyTrackingUrl}
                          className="shrink-0"
                        >
                          {copiedUrl ? (
                            <Check className="h-4 w-4" />
                          ) : (
                            <Copy className="h-4 w-4" />
                          )}
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Use this URL template in your Google Ads final URL field
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={createMutation.isPending}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isFormDisabled || !selectedGoogleAdsCampaign || selectedCount === 0}>
              {createMutation.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : isSwitchingAccount ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Loading...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Create Campaign ({selectedCount} UTMs)
                </>
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}