'use client'

import React, { useState, useEffect } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Loader2, AlertCircle, Sparkles, Link2, Copy, Check, Info } from 'lucide-react'
import { CreateCampaignData, UTMParameter } from '@/types/campaign'
import { campaignApi } from '@/services/campaign/campaign'
import { useGoogleAds } from '@/contexts/GoogleAdsContext'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { GoogleAdsCampaignError } from '@/types/errors'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'

interface CreateCampaignDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const UTM_DESCRIPTIONS: Record<string, string> = {
  utm_source: 'Identifies which site sent the traffic (e.g., google, newsletter)',
  utm_medium: 'Identifies what type of link was used (e.g., cpc, email, social)',
  utm_campaign: 'Identifies a specific campaign (e.g., summer_sale)',
  utm_id: 'Campaign ID for tracking specific campaigns',
  utm_term: 'Identifies search keywords (dynamic keyword insertion)',
  utm_content: 'Identifies what specifically was clicked (e.g., ad creative)',
}

export function CreateCampaignDialog({ open, onOpenChange }: CreateCampaignDialogProps) {
  const queryClient = useQueryClient()
  const { status, isSwitchingAccount } = useGoogleAds()
  const [formData, setFormData] = useState<CreateCampaignData>({
    name: '',
    google_ads_campaign_id: '',
    google_ads_customer_id: '',
    utm_params: [],
  })
  const [selectedGoogleAdsCampaign, setSelectedGoogleAdsCampaign] = useState<any | null>(
    null
  )
  const [autoGeneratedUTMs, setAutoGeneratedUTMs] = useState<UTMParameter[]>([])
  const [copiedUrl, setCopiedUrl] = useState(false)

  const {
    data: googleAdsCampaigns,
    isLoading: googleAdsCampaignsLoading,
    error: fetchError,
  } = useQuery<any[], GoogleAdsCampaignError>({
    queryKey: ['googleAdsCampaigns', status?.customer_id],
    queryFn: async () => {
      const result = await campaignApi.googleAdsCampaign(status?.customer_id || '')
      return result
    },
    enabled: !!status?.customer_id && !isSwitchingAccount,
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  })

  useEffect(() => {
    if (selectedGoogleAdsCampaign) {
      const campaignName = selectedGoogleAdsCampaign.name
      const campaignId = selectedGoogleAdsCampaign.id

      const slug = campaignName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')

      const utmParams: UTMParameter[] = [
        {
          key: 'utm_source',
          value: 'google',
          selected: true,
          description: UTM_DESCRIPTIONS.utm_source,
        },
        {
          key: 'utm_medium',
          value: 'cpc',
          selected: true,
          description: UTM_DESCRIPTIONS.utm_medium,
        },
        {
          key: 'utm_campaign',
          value: slug,
          selected: true,
          description: UTM_DESCRIPTIONS.utm_campaign,
        },
        {
          key: 'utm_id',
          value: campaignId,
          selected: true,
          description: UTM_DESCRIPTIONS.utm_id,
        },
        {
          key: 'utm_term',
          value: '{keyword}',
          selected: false,
          description: UTM_DESCRIPTIONS.utm_term,
        },
        {
          key: 'utm_content',
          value: '{creative}',
          selected: false,
          description: UTM_DESCRIPTIONS.utm_content,
        },
      ]

      setAutoGeneratedUTMs(utmParams)
      setFormData((prev) => ({
        ...prev,
        name: campaignName,
        google_ads_campaign_id: campaignId,
        google_ads_customer_id: status?.customer_id || '',
        utm_params: utmParams,
        google_ads_campaign_data: selectedGoogleAdsCampaign,
      }))
    }
  }, [selectedGoogleAdsCampaign, status?.customer_id])

  useEffect(() => {
    if (status?.customer_id) {
      setSelectedGoogleAdsCampaign(null)
      setAutoGeneratedUTMs([])
    }
  }, [status?.customer_id])

  const createMutation = useMutation({
    mutationFn: campaignApi.create,
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['campaigns'] })
      onOpenChange(false)
      resetForm()
    },
    onError: (error: any) => {
      console.error('Failed to create campaign:', error)
    },
  })

  const resetForm = () => {
    setFormData({
      name: '',
      google_ads_campaign_id: '',
      google_ads_customer_id: '',
      utm_params: [],
    })
    setSelectedGoogleAdsCampaign(null)
    setAutoGeneratedUTMs([])
    setCopiedUrl(false)
  }

  const handleUTMToggle = (index: number) => {
    setAutoGeneratedUTMs((prev) => {
      const updated = [...prev]
      updated[index] = { ...updated[index], selected: !updated[index].selected }

      setFormData((prevForm) => ({
        ...prevForm,
        utm_params: updated,
      }))

      return updated
    })
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!selectedGoogleAdsCampaign) {
      return
    }

    const selectedUTMs = autoGeneratedUTMs.filter((utm) => utm.selected)
    if (selectedUTMs.length === 0) {
      return
    }

    createMutation.mutate({
      ...formData,
      utm_params: autoGeneratedUTMs,
    })
  }

  const generateTrackingUrl = () => {
    const baseUrl = 'https://yourwebsite.com/'
    const selectedUTMs = autoGeneratedUTMs.filter((utm) => utm.selected)
    const params = selectedUTMs.map((utm) => `${utm.key}=${utm.value}`).join('&')
    return params ? `${baseUrl}?${params}` : baseUrl
  }

  const copyTrackingUrl = () => {
    navigator.clipboard.writeText(generateTrackingUrl())
    setCopiedUrl(true)
    setTimeout(() => setCopiedUrl(false), 2000)
  }

  const isLoading = googleAdsCampaignsLoading || isSwitchingAccount
  const isFormDisabled = isLoading || createMutation.isPending
  const selectedCount = autoGeneratedUTMs.filter((utm) => utm.selected).length

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {/* <Sparkles className="h-5 w-5 text-[#ff8904]" /> */}
            Create New Campaign
          </DialogTitle>
          <DialogDescription>
            Select a Google Ads campaign and choose which UTM parameters to track.
          </DialogDescription>
        </DialogHeader>

        {isSwitchingAccount && (
          <Alert className="mb-4 bg-[#ff8904]/10 border-[#ff8904]/30">
            <Loader2 className="h-4 w-4 animate-spin text-[#ff8904]" />
            <AlertDescription className="text-gray-800">
              Switching accounts... Please wait while we load your campaigns.
            </AlertDescription>
          </Alert>
        )}

        {fetchError && !isSwitchingAccount && (
          <Alert variant="destructive" className="mb-4">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <p className="text-sm font-medium mb-2">Error: {fetchError.message}</p>
              {fetchError.customer_id && (
                <div className="text-xs space-y-1">
                  <p>
                    Customer ID:{' '}
                    <code className="bg-destructive/20 px-1 py-0.5 rounded">
                      {fetchError.customer_id}
                    </code>
                  </p>
                  {fetchError.customer_name && <p>Account: {fetchError.customer_name}</p>}
                  {fetchError.error_code && (
                    <p>
                      Error Code:{' '}
                      <code className="bg-destructive/20 px-1 py-0.5 rounded">
                        {fetchError.error_code}
                      </code>
                    </p>
                  )}
                </div>
              )}
            </AlertDescription>
          </Alert>
        )}

        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="googleAdsCampaign">Select Google Ads Campaign *</Label>
              {isLoading ? (
                <Select disabled>
                  <SelectTrigger className="w-full">
                    <SelectValue
                      placeholder={
                        isSwitchingAccount
                          ? 'Switching accounts...'
                          : 'Loading campaigns...'
                      }
                    />
                  </SelectTrigger>
                </Select>
              ) : googleAdsCampaigns?.length === 0 ? (
                <div className="p-4 border rounded-md bg-muted text-center">
                  <p className="text-sm text-gray-600">
                    No Google Ads campaigns found for this account.
                  </p>
                </div>
              ) : (
                <Select
                  onValueChange={(value) => {
                    const campaign = googleAdsCampaigns?.find((c) => c.id === value)
                    setSelectedGoogleAdsCampaign(campaign)
                  }}
                  value={selectedGoogleAdsCampaign?.id || ''}
                  disabled={isFormDisabled}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select a campaign" />
                  </SelectTrigger>
                  <SelectContent>
                    {googleAdsCampaigns?.map((campaign: any) => (
                      <SelectItem key={campaign.id} value={campaign.id}>
                        <div className="flex items-center justify-between gap-2 w-full">
                          <span className="truncate">{campaign.name}</span>
                          <Badge
                            variant={
                              campaign.status === 'ENABLED' ? 'default' : 'secondary'
                            }
                            className={
                              campaign.status === 'ENABLED'
                                ? 'bg-tertiary/20 text-tertiary border-tertiary/30'
                                : ''
                            }
                          >
                            {campaign.status}
                          </Badge>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="name">Campaign Name</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="Auto-filled from Google Ads"
                disabled={isFormDisabled}
                className="bg-muted"
              />
            </div>

            {autoGeneratedUTMs.length > 0 && (
              <Card className="bg-white">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-medium">UTM Parameters</CardTitle>
                  <CardDescription className="text-xs">
                    Select the tracking parameters you want to include
                  </CardDescription>
                </CardHeader>

                <CardContent className="space-y-2">
                  {autoGeneratedUTMs.map((utm, idx) => (
                    <div
                      key={idx}
                      className={`
            flex items-start gap-3 p-3 rounded-md border
            ${utm.selected ? 'bg-white' : 'bg-muted/20'}
          `}
                    >
                      <Checkbox
                        id={`utm-${idx}`}
                        checked={utm.selected}
                        onCheckedChange={() => handleUTMToggle(idx)}
                        disabled={isFormDisabled}
                        className="mt-1"
                      />
                      <div className="flex-1 min-w-0">
                        <Label
                          htmlFor={`utm-${idx}`}
                          className="text-sm font-medium cursor-pointer flex items-center gap-1"
                        >
                          <code className="text-xs px-1 py-0.5 rounded bg-muted font-mono">
                            {utm.key}
                          </code>
                          <span>=</span>
                          <code className="text-xs px-1 py-0.5 rounded bg-muted font-mono truncate">
                            {utm.value}
                          </code>
                        </Label>
                        {utm.description && (
                          <p className="text-xs text-muted-foreground mt-1">
                            {utm.description}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}

                  {selectedCount > 0 && (
                    <div className="space-y-2 pt-3 border-t">
                      <Label className="text-xs">Tracking URL Preview</Label>
                      <div className="flex gap-2">
                        <Input
                          value={generateTrackingUrl()}
                          readOnly
                          className="font-mono text-xs"
                        />
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          onClick={copyTrackingUrl}
                          disabled={isFormDisabled}
                        >
                          {copiedUrl ? (
                            <Check className="h-4 w-4" />
                          ) : (
                            <Copy className="h-4 w-4" />
                          )}
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Copy and paste this URL into your Google Ads final URL field
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={createMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={
                isFormDisabled || !selectedGoogleAdsCampaign || selectedCount === 0
              }
              className="bg-[#ff8904] hover:bg-[#ff8904]/90"
            >
              {createMutation.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : isSwitchingAccount ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Loading...
                </>
              ) : (
                <>
                  {/* <Sparkles className="mr-2 h-4 w-4" /> */}
                  Create Campaign ({selectedCount} UTMs)
                </>
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
