import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const faqData = [
  {
    question: "What is the CarbonCut Marketing CO₂e Calculator?",
    answer: "The CarbonCut Marketing CO₂e Calculator is a science-based tool that helps brands estimate the carbon emissions generated by their marketing activities. It calculates emissions across channels—including digital, print, and production—providing campaign-level CO₂e insights to support sustainable decision-making.",
    category: "basics"
  },
  {
    question: "How do I use the CarbonCut Marketing CO₂e Calculator?",
    answer: "Simply select your marketing channel, enter your activity data (such as impressions, clicks, and/ or spend), choose your market region, and our calculator will estimate residual emissions using verified emission factors and real-time environmental data.",
    category: "usage"
  },
  {
    question: "What equivalents does the calculator provide?",
    answer: "The calculator displays your emissions in kg CO₂e and tons CO₂e, along with real-world equivalents such as car miles driven, trees required to offset, and household electricity use.Results can be broken down by channel, geography, and emission scope for deeper insight.",
    category: "features"
  },
  {
    question: "Who should use the CarbonCut Marketing CO₂e Calculator?",
    answer: "Designed for marketing teams, ESG and sustainability leads, CMOs, and agencies, the tool supports both campaign planning and corporate carbon reporting (Scope 3 – Category 1 & 9)",
    category: "audience"
  },
  {
    question: "What other names or terms are used for this type of tool?",
    answer: "Other common names include Carbon Footprint Estimator for Advertising, Scope 3 Marketing Emissions Calculator, or Net-Zero Marketing Dashboard.",
    category: "terminology"
  },
  {
    question: "How can I install the CarbonCut Marketing CO₂e Calculator on my website?",
    answer: "Check out CarbonLive — our enterprise API that provides real-time carbon emission API for reporting and enables automatic offsetting for your marketing activities as they run.",
    category: "integration"
  },
   {
    question: "How accurate is the CarbonCut Marketing CO₂e Calculator?",
    answer: "Our methodology follows the GHG Protocol, SBTi Corporate Net-Zero Standard, and DIMPACT benchmarks. All emission factors are updated annually and regionally calibrated using data from IEA, DEFRA, and national grid intensities for 2025.",
    category: "integration"
  }
];

// const getCategoryInfo = (category: string) => {
//   switch (category) {
//     case "basics":
//       return { color: "bg-blue-100 text-blue-700 border-blue-200", label: "Basics" };
//     case "usage":
//       return { color: "bg-tertiary/10 text-tertiary border-tertiary/20", label: "Usage" };
//     case "features":
//       return { color: "bg-orange-100 text-orange-700 border-orange-200", label: "Features" };
//     case "audience":
//       return { color: "bg-purple-100 text-purple-700 border-purple-200", label: "Audience" };
//     case "terminology":
//       return { color: "bg-gray-100 text-gray-700 border-gray-200", label: "Terms" };
//     case "integration":
//       return { color: "bg-green-100 text-green-700 border-green-200", label: "Integration" };
//     default:
//       return { color: "bg-gray-100 text-gray-700 border-gray-200", label: "General" };
//   }
// };

export default function CalculatorFAQ() {
  return (
    <div className="bg-white px-6 py-14 space-y-6">
      {/* Header */}
      <div className="text-center space-y-4">
        <h2 className="text-3xl lg:text-5xl  text-gray-900">
           <span className="text-tertiary"> About CarbonCut</span> Equivalent CO₂e
          <br />
          <span className="text-gray-900">Calculator</span>
        </h2>

        <p className="text-gray-600 max-w-3xl mx-auto leading-relaxed">
          The CarbonCut Calculator helps you understand the {" "} <strong className="text-orange-500">  true climate impact of your marketing activities. </strong> {" "} It uses independently verified emission factors and up-to-date environmental datasets to convert campaign inputs into accurate CO₂e estimates.
        </p>
      </div>

      {/* FAQ Accordion */}
      <div className="max-w-4xl mx-auto">
        <Accordion type="single" collapsible className="space-y-4">
          {faqData.map((faq, index) => {
            // const categoryInfo = getCategoryInfo(faq.category);

            return (
              <AccordionItem
                key={index}
                value={`item-${index}`}
              >
                <AccordionTrigger className="px-6 py-4 text-left hover:no-underline group">
                  <div className="flex items-start gap-4 w-full">
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-gray-900 group-hover:text-tertiary transition-colors">
                        {faq.question}
                      </h3>
                    </div>
                  </div>
                </AccordionTrigger>

                <AccordionContent className="px-6 pb-6">
                  <p className="text-gray-600 leading-relaxed">
                    {faq.answer}
                  </p>
                </AccordionContent>
              </AccordionItem>
            );
          })}
        </Accordion>
      </div>
    </div>
  );
}
