import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const faqData = [
  {
    question: "What is the CarbonCut Marketing CO₂e Calculator?",
    answer:
      "The CarbonCut Marketing CO₂e Calculator is a science-based tool that helps brands estimate the carbon emissions generated by their marketing activities. It calculates emissions across channels—including digital, print, and production—providing campaign-level CO₂e insights to support sustainable decision-making.",
    category: "basics",
  },
  {
    question: "How do I use the CarbonCut Marketing CO₂e Calculator?",
    answer:
      "Simply select your marketing channel, enter your activity data (such as impressions, clicks, and/ or spend), choose your market region, and our calculator will estimate residual emissions using verified emission factors and real-time environmental data.",
    category: "usage",
  },
  {
    question: "What equivalents does the calculator provide?",
    answer:
      "The calculator displays your emissions in kg CO₂e and tons CO₂e, along with real-world equivalents such as car miles driven, trees required to offset, and household electricity use.Results can be broken down by channel, geography, and emission scope for deeper insight.",
    category: "features",
  },
  {
    question: "Who should use the CarbonCut Marketing CO₂e Calculator?",
    answer:
      "Designed for marketing teams, ESG and sustainability leads, CMOs, and agencies, the tool supports both campaign planning and corporate carbon reporting (Scope 3 – Category 1 & 9)",
    category: "audience",
  },
  {
    question: "What other names or terms are used for this type of tool?",
    answer:
      "Other common names include Carbon Footprint Estimator for Advertising, Scope 3 Marketing Emissions Calculator, or Net-Zero Marketing Dashboard.",
    category: "terminology",
  },
  {
    question:
      "How can I install the CarbonCut Marketing CO₂e Calculator on my website?",
    answer:
      "Check out CarbonLive — our enterprise API that provides real-time carbon emission API for reporting and enables automatic offsetting for your marketing activities as they run.",
    category: "integration",
  },
  {
    question: "How accurate is the CarbonCut Marketing CO₂e Calculator?",
    answer:
      "Our methodology follows the GHG Protocol, SBTi Corporate Net-Zero Standard, and DIMPACT benchmarks. All emission factors are updated annually and regionally calibrated using data from IEA, DEFRA, and national grid intensities for 2025.",
    category: "integration",
  },
];

// const getCategoryInfo = (category: string) => {
//   switch (category) {
//     case "basics":
//       return { color: "bg-blue-100 text-blue-700 border-blue-200", label: "Basics" };
//     case "usage":
//       return { color: "bg-tertiary/10 text-tertiary border-tertiary/20", label: "Usage" };
//     case "features":
//       return { color: "bg-orange-100 text-orange-700 border-orange-200", label: "Features" };
//     case "audience":
//       return { color: "bg-purple-100 text-purple-700 border-purple-200", label: "Audience" };
//     case "terminology":
//       return { color: "bg-gray-100 text-gray-700 border-gray-200", label: "Terms" };
//     case "integration":
//       return { color: "bg-green-100 text-green-700 border-green-200", label: "Integration" };
//     default:
//       return { color: "bg-gray-100 text-gray-700 border-gray-200", label: "General" };
//   }
// };


  {/* Header */}
      {/* <div className="text-center space-y-6 mb-24">
        <h2 className="text-4xl lg:text-6xl font-light tracking-tight" style={{ color: "#080c04" }}>
          <span style={{ color: "#b0ea1d" }}>About CarbonCut</span> Equivalent CO₂e
          <br />
          <span style={{ color: "#080c04" }}>Calculator</span>
        </h2>

        <p className="max-w-4xl mx-auto leading-relaxed text-lg" style={{ color: "#6c5f31" }}>
          The CarbonCut Calculator helps you understand the{" "}
          <strong className="font-semibold" style={{ color: "#F0db18" }}>
            true climate impact of your marketing activities.
          </strong>{" "}
          It uses independently verified emission factors and up-to-date
          environmental datasets to convert campaign inputs into accurate CO₂e
          estimates.
        </p>
      </div> */}


export default function CalculatorFAQ() {
  return (
    <div className="px-4 sm:px-6 md:px-12 lg:px-24 py-12 sm:py-16 md:py-20 lg:py-28" style={{ background: "#fcfdf6" }}>

      <div className="max-w-[1700px] mx-auto space-y-12 sm:space-y-16 md:space-y-24">

        {/* SECTION 1 */}
        <div className="space-y-8 sm:space-y-12 md:space-y-16">

          {/* CLEAN FULL-WIDTH DIVIDER */}
          <div className="w-full border-t-2 border-dotted" style={{ borderColor: "#d1cebb" }}></div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 sm:gap-8 md:gap-12">

            {/* LEFT TITLE */}
            <div className="lg:col-span-4">
              <h3
                className="text-xl sm:text-2xl lg:text-3xl font-bold uppercase tracking-wider text-left"
                style={{ color: "#080c04" }}
              >
                General FAQ
              </h3>
            </div>

            {/* Spacer */}
            <div className="hidden lg:block lg:col-span-2"></div>

            {/* RIGHT SIDE ACCORDION */}
            <div className="lg:col-span-6">
              <Accordion type="single" collapsible className="space-y-0">
                {faqData.slice(0, 3).map((faq, index) => (
                  <AccordionItem
                    key={index}
                    value={`general-${index}`}
                    className="border-b"
                    style={{ borderColor: "#d1cebb" }}
                  >
                    <AccordionTrigger
                      className="py-4 sm:py-6 px-2 sm:px-4 -mx-2 sm:-mx-4 hover:no-underline rounded-lg"
                      style={{ color: "#080c04" }}
                    >
                      <h4 className="text-base sm:text-lg lg:text-xl font-normal pr-4 text-left">
                        {faq.question}
                      </h4>
                    </AccordionTrigger>

                    <AccordionContent
                      className="pb-4 sm:pb-6 px-2 sm:px-4 text-sm sm:text-base lg:text-lg leading-relaxed"
                      style={{ color: "#6c5f31" }}
                    >
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          </div>
        </div>

        {/* SECTION 2 */}
        <div className="space-y-8 sm:space-y-12 md:space-y-16">

          {/* CLEAN FULL-WIDTH DIVIDER */}
          <div className="w-full border-t-2 border-dotted" style={{ borderColor: "#d1cebb" }}></div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 sm:gap-8 md:gap-12">

            {/* LEFT TITLE */}
            <div className="lg:col-span-4">
              <h3
                className="text-xl sm:text-2xl lg:text-3xl font-bold uppercase tracking-wider text-left"
                style={{ color: "#080c04" }}
              >
                About CarbonCut Equivalent CO₂e Calculator
              </h3>
            </div>

            {/* Spacer */}
            <div className="hidden lg:block lg:col-span-2"></div>

            {/* RIGHT ACCORDION */}
            <div className="lg:col-span-6">
              <Accordion type="single" collapsible className="space-y-0">
                {faqData.slice(3).map((faq, index) => (
                  <AccordionItem
                    key={index}
                    value={`solution-${index}`}
                    className="border-b"
                    style={{ borderColor: "#d1cebb" }}
                  >
                    <AccordionTrigger
                      className="py-4 sm:py-6 px-2 sm:px-4 -mx-2 sm:-mx-4 hover:no-underline rounded-lg"
                      style={{ color: "#080c04" }}
                    >
                      <h4 className="text-base sm:text-lg lg:text-xl font-normal pr-4 text-left">
                        {faq.question}
                      </h4>
                    </AccordionTrigger>

                    <AccordionContent
                      className="pb-4 sm:pb-6 px-2 sm:px-4 text-sm sm:text-base lg:text-lg leading-relaxed"
                      style={{ color: "#6c5f31" }}
                    >
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}


