"use client";

import { AlertCircleIcon } from "lucide-react";
import FloatingInput from "../ui/FloatingInput";
import { Alert, AlertDescription, AlertTitle } from "../ui/alert";
import Dropdown from "../ui/dropdown";
import { CdnData } from "@/types/onboarding";
import clsx from "clsx";

export interface Props {
  data: CdnData;
  onDataChange: (data: CdnData) => void;
  onBack: () => void;
  onNext: () => void;
  canProceed: boolean;
}

export default function Cdn({ data, onDataChange, onBack, onNext, canProceed }: Props) {
  return (
    <div className="w-full space-y-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <Dropdown
          placeholder="CDN Provider"
          options={[
            { label: "Cloudflare", value: "cloudflare" },
            { label: "AWS", value: "aws" },
            { label: "Azure", value: "azure" },
            { label: "Google Cloud", value: "google" },
            { label: "Others", value: "others" },
  
          ]}
          size="big"
          value={data.cdnProvider}
          onChange={(value) => onDataChange({ ...data, cdnProvider: value })}
        />

        <FloatingInput
          type="number"
          placeholder="Monthly GB Transferred"
          size="big"
          value={data.monthlyGBTransferred}
          onChange={(value) => onDataChange({ ...data, monthlyGBTransferred: value })}
        />

        <Dropdown
          placeholder="Regions"
          options={[
            { label: "Global", value: "global" },
            { label: "North America", value: "na" },
            { label: "Europe", value: "eu" },
            { label: "Asia Pacific", value: "apac" },
          ]}
          size="big"
          value={data.regions}
          onChange={(value) => onDataChange({ ...data, regions: value })}
        />
      </div>
       <Alert >
        <AlertCircleIcon />
        <AlertTitle> Content Delivery Network (CDN) Emissions</AlertTitle>
        <AlertDescription>
          <p>Emissions from global content distribution and data transfer</p>
          <ul className="list-inside list-disc text-sm">
            <li>Generated by delivering digital content closer to end users</li>
            <li>Includes edge servers, caching, and high-volume data transmission</li>
            <li>Includes compute, storage, networking, and managed cloud services</li>
          </ul>
        </AlertDescription>
      </Alert>

      {/* ACTIONS */}
      <div className="flex items-center justify-between pt-6 border-t border-neutral-200">
        <button
          onClick={onBack}
          className="min-w-[140px] rounded-lg border border-neutral-300 px-8 py-3 text-base font-medium text-neutral-700 hover:bg-neutral-50 transition-colors"
        >
          Back
        </button>

        <button
          onClick={onNext}
          disabled={!canProceed}
          className={clsx(
            "min-w-[140px] rounded-lg px-8 py-3 text-base font-medium text-white transition-all",
            canProceed 
              ? "bg-black hover:bg-neutral-800 cursor-pointer shadow-sm hover:shadow" 
              : "bg-neutral-300 cursor-not-allowed"
          )}
        >
          Continue
        </button>
      </div>
    </div>
  );
}
