"use client";

import React from "react";
import { AlertCircleIcon } from "lucide-react";
import FloatingInput from "../ui/FloatingInput";
import { Alert, AlertDescription, AlertTitle } from "../ui/alert";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CdnData } from "@/types/onboarding";
import clsx from "clsx";

export interface Props {
  data: CdnData;
  onDataChange: (data: CdnData) => void;
  onBack: () => void;
  onNext: () => void;
  onSkip: () => void;
  canProceed: boolean;
}

export default function Cdn({
  data,
  onDataChange,
  onSkip,
  onBack,
  onNext,
  canProceed,
}: Props) {
  return (
    <div className="w-full space-y-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {/* CDN Provider */}
        <div className="space-y-2">
          <label className="text-sm font-medium">CDN Provider</label>
          <Select
            value={data.cdnProvider}
            onValueChange={(value) =>
              onDataChange({ ...data, cdnProvider: value })
            }
          >
            <SelectTrigger className="h-14">
              <SelectValue placeholder="Select CDN provider" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="cloudflare">Cloudflare</SelectItem>
              <SelectItem value="aws">AWS</SelectItem>
              <SelectItem value="azure">Azure</SelectItem>
              <SelectItem value="google">Google Cloud</SelectItem>
              <SelectItem value="others">Others</SelectItem>
            </SelectContent>
          </Select>
        </div>

       

        {/* Regions */}
        <div className="space-y-2">
          <label className="text-sm font-medium">Regions</label>
          <Select
            value={data.regions}
            onValueChange={(value) =>
              onDataChange({ ...data, regions: value })
            }
          >
            <SelectTrigger className="h-14">
              <SelectValue placeholder="Select region" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="global">Global</SelectItem>
              <SelectItem value="na">North America</SelectItem>
              <SelectItem value="eu">Europe</SelectItem>
              <SelectItem value="apac">Asia Pacific</SelectItem>
            </SelectContent>
          </Select>
        </div>


         {/* Monthly GB Transferred */}
        <FloatingInput
          type="number"
          placeholder="Monthly GB Transferred"
          size="big"
          value={data.monthlyGBTransferred}
          onChange={(value) =>
            onDataChange({ ...data, monthlyGBTransferred: value })
          }
        />
      </div>

      <Alert>
        <AlertCircleIcon />
        <AlertTitle>Content Delivery Network (CDN) Emissions</AlertTitle>
        <AlertDescription>
          <p>Emissions from global content distribution and data transfer</p>
          <ul className="list-inside list-disc text-sm">
            <li>Generated by delivering digital content closer to end users</li>
            <li>Includes edge servers, caching, and high-volume data transmission</li>
            <li>Includes compute, storage, networking, and managed services</li>
          </ul>
        </AlertDescription>
      </Alert>

      {/* ACTIONS */}
      <div className="flex items-center justify-between pt-6 border-t border-neutral-200">
        <button
          onClick={onBack}
          className="min-w-[140px] rounded-lg border border-neutral-300 px-8 py-3 text-base font-medium text-neutral-700 hover:bg-[#d1cebb] transition-colors"
        >
          Back
        </button>

        <div className="flex items-center gap-4">
          <button
            onClick={onSkip}
            className="min-w-[140px] rounded-lg border border-neutral-300 px-8 py-3 text-base font-medium text-neutral-700 hover:bg-[#d1cebb] transition-colors"
          >
            Skip
          </button>

          <button
            onClick={onNext}
            disabled={!canProceed}
            className={clsx(
              "min-w-[140px] rounded-lg px-8 py-3 text-base font-medium text-white transition-all",
              canProceed
                ? "bg-black hover:bg-neutral-800 cursor-pointer shadow-sm hover:shadow"
                : "bg-neutral-300 cursor-not-allowed"
            )}
          >
            Continue
          </button>
        </div>
      </div>
    </div>
  );
}
