"use client";

import { AlertCircleIcon, CheckCircle2Icon, PopcornIcon } from "lucide-react";
import FloatingInput from "../ui/FloatingInput";
import { Alert, AlertDescription, AlertTitle } from "../ui/alert";
import Dropdown from "../ui/dropdown";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { CloudProviderData } from "@/types/onboarding";
import clsx from "clsx";

interface Props {
  data: CloudProviderData;
  onDataChange: (data: CloudProviderData) => void;
  onBack: () => void;
  onNext: () => void;
  canProceed: boolean;
}

export default function CloudProvider({ data, onDataChange, onBack , onNext, canProceed }: Props) {
  const handleTabChange = (value: string) => {
    onDataChange({
      ...data,
      tabType: value as "Manual" | "Upload",
      uploadedFile: value === "Manual" ? null : data.uploadedFile,
    });
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null;
    onDataChange({
      ...data,
      uploadedFile: file,
    });
  };

  return (
    <div className="w-full space-y-8">
      <Tabs value={data.tabType} onValueChange={handleTabChange}>
        <TabsList className="bg-[#fcfdf6] p-1 rounded-lg">
          <TabsTrigger 
            value="Manual"
            className="px-6 py-2 rounded-md data-[state=active]:bg-[#6c5f31] data-[state=active]:text-white data-[state=active]:shadow-sm"
          >
            Manual
          </TabsTrigger>
          <TabsTrigger 
            value="Upload"
            className="px-6 py-2 rounded-md data-[state=active]:bg-[#6c5f31] data-[state=active]:text-white data-[state=active]:shadow-sm"
          >
            Upload
          </TabsTrigger>
        </TabsList>

        <div className="mt-8">
          <TabsContent value="Manual" className="mt-0">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <Dropdown
                placeholder="Monthly cost"
                options={[
                  { label: "Monthly", value: "monthly" },
                  { label: "Annual", value: "annual" },
                ]}
                size="big"
                value={data.monthlyCost}
                onChange={(value) =>
                  onDataChange({ ...data, monthlyCost: value })
                }
              />

              <FloatingInput
                type="number"
                placeholder="Actual cost (USD)"
                size="big"
                value={data.actualCost}
                onChange={(value) =>
                  onDataChange({ ...data, actualCost: value })
                }
              />

              <FloatingInput
                type="number"
                placeholder="Monthly Hours Usage"
                size="big"
                value={data.monthlyHoursUsage}
                onChange={(value) =>
                  onDataChange({ ...data, monthlyHoursUsage: value })
                }
              />

              <Dropdown
                placeholder="Region"
                options={[
                  { label: "AWS US EAST (N. Virginia)", value: "east" },
                  { label: "AWS US WEST (California)", value: "west" },
                  { label: "AWS EU WEST (Ireland)", value: "eu" },
                  { label: "AWS APAC (Singapore)", value: "apac" },
                ]}
                size="big"
                value={data.region}
                onChange={(value) =>
                  onDataChange({ ...data, region: value })
                }
              />
            </div> 

            <div className="mt-8">
               <Alert >
        <AlertCircleIcon />
        <AlertTitle> Cloud Provider Emissions</AlertTitle>
        <AlertDescription>
          <p>Emissions from cloud infrastructure and hosted workloads</p>
          <ul className="list-inside list-disc text-sm">
            <li>Covers emissions generated by cloud data centers running applications and storage</li>
            <li>Influenced by data center energy efficiency and renewable energy usage</li>
            <li>Includes compute, storage, networking, and managed cloud services</li>
          </ul>
        </AlertDescription>
      </Alert>
            </div>
          </TabsContent>

          <TabsContent value="Upload" className="mt-0">
            <div className="space-y-4">
              <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 rounded-lg border border-[#d1cebb]  px-6 py-4">
                <span className={clsx("text-base truncate", data.uploadedFile ? "text-neutral-900 font-medium" : "text-neutral-500")}>
                  {data.uploadedFile ? data.uploadedFile.name : "Choose file"}
                </span>

                <label className="cursor-pointer rounded-lg bg-black px-6 py-3 text-sm font-medium text-white hover:bg-neutral-800 transition-colors whitespace-nowrap">
                  Browse
                  <input 
                    type="file" 
                    accept=".csv" 
                    className="hidden" 
                    onChange={handleFileChange}
                  />
                </label>
              </div>
            </div>
            <div>
                <Alert className="mt-8">
        <AlertCircleIcon />
        <AlertTitle>AWS Customer Carbon Footprint Tool</AlertTitle>
        <AlertDescription>
          <p>Measure and understand carbon emissions from your AWS usage</p>
          <ul className="list-inside list-disc text-sm">
            <li>Sign in to the AWS Management Console using your billing or sustainability account</li>
            <li>Navigate to Billing and Cost Management and open Customer Carbon Footprint Tool</li>
            <li>Select the date range you want to analyze (monthly or yearly emissions)</li>
            <li>Review emissions broken down by AWS service and region</li>
            <li>Click Download Report to export your carbon footprint data as a CSV file</li>
            <li>Upload the downloaded file into your sustainability or ESG reporting platform</li>
          </ul>
        </AlertDescription>
      </Alert>
            </div>
          </TabsContent>
        </div>

      
      </Tabs>

      {/* ACTIONS */}
    

      
   <div className="flex items-center justify-between pt-6 border-t border-neutral-200">
          <button
            onClick={onBack}
            className="min-w-[140px] rounded-lg border border-neutral-300 px-8 py-3 text-base font-medium text-neutral-700 hover:bg-neutral-50 transition-colors"
          >
            Back
          </button>
  
          <button
            onClick={onNext}
            disabled={!canProceed}
            className={clsx(
              "min-w-[140px] rounded-lg px-8 py-3 text-base font-medium text-white transition-all",
              canProceed 
                ? "bg-black hover:bg-neutral-800 cursor-pointer shadow-sm hover:shadow" 
                : "bg-neutral-300 cursor-not-allowed"
            )}
          >
            Continue
          </button>
        </div>
     
    </div>
  );
}
