"use client"

import React, { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Loader2, AlertCircle, Tag, Sparkles } from "lucide-react"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { useGoogleAds } from "@/contexts/GoogleAdsContext"
import { campaignApi } from "@/services/campaign/campaign"
import { CreateCampaignData, UTMParameter } from "@/types/campaign"
import { Skeleton } from "@/components/ui/skeleton"
import { toast } from "sonner"
import { useRouter } from "next/navigation"
import { makeRequest } from "@/contexts/AuthContext"

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000/api/v1"

interface CampaignCreationStepProps {
  onComplete: () => void
}

const UTM_DESCRIPTIONS: Record<string, string> = {
  utm_source: "Identifies which site sent the traffic (e.g., google, newsletter)",
  utm_medium: "Identifies what type of link was used (e.g., cpc, email, social)",
  utm_campaign: "Identifies a specific campaign (e.g., summer_sale)",
  utm_id: "Campaign ID for tracking specific campaigns",
  utm_term: "Identifies search keywords (dynamic keyword insertion)",
  utm_content: "Identifies what specifically was clicked (e.g., ad creative)",
}

export default function CampaignCreationStep({ onComplete }: CampaignCreationStepProps) {
  const router = useRouter()
  const queryClient = useQueryClient()
  const { status, isSwitchingAccount } = useGoogleAds()
  const [formData, setFormData] = useState<CreateCampaignData>({
    name: "",
    google_ads_campaign_id: "",
    google_ads_customer_id: "",
    utm_params: [],
  })
  const [selectedGoogleAdsCampaign, setSelectedGoogleAdsCampaign] = useState<any | null>(null)
  const [autoGeneratedUTMs, setAutoGeneratedUTMs] = useState<UTMParameter[]>([])

  const { data: googleAdsCampaigns, isLoading: googleAdsCampaignsLoading } = useQuery({
    queryKey: ["googleAdsCampaigns", status?.customer_id],
    queryFn: async () => {
      const result = await campaignApi.googleAdsCampaign(status?.customer_id || "")
      return result
    },
    enabled: !!status?.customer_id && !isSwitchingAccount,
    staleTime: 5 * 60 * 1000,
  })

  useEffect(() => {
    if (selectedGoogleAdsCampaign) {
      const campaignName = selectedGoogleAdsCampaign.name
      const campaignId = selectedGoogleAdsCampaign.id

      const slug = campaignName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "")

      const utmParams: UTMParameter[] = [
        {
          key: "utm_source",
          value: "google",
          selected: true,
          description: UTM_DESCRIPTIONS.utm_source,
        },
        {
          key: "utm_medium",
          value: "cpc",
          selected: true,
          description: UTM_DESCRIPTIONS.utm_medium,
        },
        {
          key: "utm_campaign",
          value: slug,
          selected: true,
          description: UTM_DESCRIPTIONS.utm_campaign,
        },
        {
          key: "utm_id",
          value: campaignId,
          selected: true,
          description: UTM_DESCRIPTIONS.utm_id,
        },
        {
          key: "utm_term",
          value: "{keyword}",
          selected: false,
          description: UTM_DESCRIPTIONS.utm_term,
        },
        {
          key: "utm_content",
          value: "{creative}",
          selected: false,
          description: UTM_DESCRIPTIONS.utm_content,
        },
      ]

      setAutoGeneratedUTMs(utmParams)
      setFormData((prev) => ({
        ...prev,
        name: campaignName,
        google_ads_campaign_id: campaignId,
        google_ads_customer_id: status?.customer_id || "",
        utm_params: utmParams,
        google_ads_campaign_data: selectedGoogleAdsCampaign,
      }))
    }
  }, [selectedGoogleAdsCampaign, status?.customer_id])

  const createMutation = useMutation({
    mutationFn: campaignApi.create,
    onSuccess: async (data) => {
      queryClient.invalidateQueries({ queryKey: ["campaigns"] })
      toast.success(`Campaign "${data.name}" created successfully!`)
      
      // Mark campaign creation as complete
      // try {
      //   await makeRequest(`${API_BASE}/auth/onboarding-status/`, {
      //     method: "POST",
      //     body: JSON.stringify({
      //       step_key: "campaign_created",
      //       completed: true,
      //     }),
      //   })
      // } catch (error) {
      //   console.error("Failed to update campaign completion:", error)
      // }
      
      onComplete()
      
      setTimeout(() => {
        router.push("/dashboard/campaigns")
      }, 1500)
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.error || "Failed to create campaign")
    },
  })

  const toggleUTMSelection = (key: string) => {
    setAutoGeneratedUTMs((prev) => {
      const updated = prev.map((utm) => (utm.key === key ? { ...utm, selected: !utm.selected } : utm))
      setFormData((prevForm) => ({
        ...prevForm,
        utm_params: updated,
      }))
      return updated
    })
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!selectedGoogleAdsCampaign) {
      toast.error("Please select a Google Ads campaign")
      return
    }

    const selectedCount = autoGeneratedUTMs.filter((utm) => utm.selected).length
    if (selectedCount === 0) {
      toast.error("Please select at least one UTM parameter")
      return
    }

    createMutation.mutate({
      ...formData,
      utm_params: autoGeneratedUTMs,
    })
  }

  const isLoading = googleAdsCampaignsLoading || isSwitchingAccount
  const isFormDisabled = isLoading || createMutation.isPending
  const selectedCount = autoGeneratedUTMs.filter((utm) => utm.selected).length

  if (googleAdsCampaignsLoading) {
    return (
      <div className="space-y-6">
        <div>
          <Skeleton className="h-4 w-24 mb-3" />
          <Skeleton className="h-8 w-3/4 mb-4" />
          <Skeleton className="h-4 w-full mb-2" />
          <Skeleton className="h-4 w-5/6" />
        </div>
        <div className="space-y-4">
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-48 w-full" />
        </div>
      </div>
    )
  }

  return (
    <form onSubmit={handleSubmit}>
      <p className="text-xs text-tertiary font-semibold mb-3">STEP 3 OF 3</p>
      <h2 className="text-3xl font-bold text-gray-900 mb-4">Campaign Creation</h2>
      <p className="text-gray-600 text-sm mb-8 leading-relaxed">
        Select a campaign from your Google Ads account. We&apos;ll automatically generate UTM parameters and campaign
        name based on your selection.
      </p>

      {isSwitchingAccount && (
        <Alert className="mb-4">
          <Loader2 className="h-4 w-4 animate-spin" />
          <AlertDescription>Switching accounts... Please wait while we load your campaigns.</AlertDescription>
        </Alert>
      )}

      <div className="space-y-6 mb-8">
        <div className="space-y-2">
          <Label htmlFor="googleAdsCampaign">
            Select Google Ads Campaign <span className="text-red-500">*</span>
          </Label>
          {isLoading ? (
            <Select disabled>
              <SelectTrigger className="w-full">
                <SelectValue placeholder={isSwitchingAccount ? "Switching accounts..." : "Loading campaigns..."} />
              </SelectTrigger>
            </Select>
          ) : googleAdsCampaigns?.length === 0 ? (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>No Google Ads campaigns found for this account.</AlertDescription>
            </Alert>
          ) : (
            <Select
              onValueChange={(value) => {
                const campaign = googleAdsCampaigns?.find((c: any) => c.id === value)
                setSelectedGoogleAdsCampaign(campaign || null)
              }}
              disabled={isFormDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select a campaign..." />
              </SelectTrigger>
              <SelectContent>
                {googleAdsCampaigns?.map((campaign: any) => (
                  <SelectItem key={campaign.id} value={campaign.id}>
                    {campaign.name} - {campaign.status}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor="name">Campaign Name</Label>
          <Input
            id="name"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            placeholder="Auto-filled from Google Ads"
            disabled={isFormDisabled}
            className="bg-muted"
          />
        </div>

        {autoGeneratedUTMs.length > 0 && (
          <Card className="border-blue-200 bg-blue-50/30">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Tag className="h-4 w-4 text-orange-600" />
                    Select UTM Parameters
                  </CardTitle>
                  <CardDescription className="text-xs">
                    Choose which tracking parameters to include ({selectedCount} selected)
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              {autoGeneratedUTMs.map((utm) => (
                <div
                  key={utm.key}
                  className={`flex items-start gap-3 p-3 rounded-lg border bg-white transition-all ${
                    utm.selected ? "border-orange-200 shadow-sm" : "border-gray-200 opacity-60"
                  }`}
                >
                  <Checkbox
                    id={utm.key}
                    checked={utm.selected}
                    onCheckedChange={() => toggleUTMSelection(utm.key)}
                    disabled={isFormDisabled}
                    className="mt-0.5"
                  />
                  <div className="flex-1 min-w-0">
                    <label htmlFor={utm.key} className="cursor-pointer">
                      <div className="font-mono text-xs text-gray-900 mb-1 break-all">
                        {utm.key} = {utm.value}
                      </div>
                      <p className="text-xs text-gray-600">{utm.description}</p>
                    </label>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        )}
      </div>

     
      <div className="flex flex-1 gap-2">
         <Button
        type="submit"
        disabled={isFormDisabled || !selectedGoogleAdsCampaign || selectedCount === 0}
        className="bg-tertiary hover:bg-tertiary/90"
      >
        {createMutation.isPending ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Creating Campaign...
          </>
        ) : (
          <>
            <Sparkles className="mr-2 h-4 w-4" />
            Create Campaign 
          </>
        )}
      </Button>
      <Button className="bg-white text-gray-900 hover:bg-gray-100 shadow">
        Skip
      </Button>
      {/* <p className="text-sm">You can create Campaigns inside Dashboard </p> */}
      </div>
    </form>
  )
}